config/routes.rb
NrugCoverletter::Application.routes.draw do
  resources :cover_letters

  resources :skills

  devise_for :users

  root 'cover_letters#index'

end

app/models/cover_letter.rb
class CoverLetter < ActiveRecord::Base
  belongs_to :user

  def addressee_or_generic
    return addressee unless addressee.blank?
    "Sir or Madam"
  end

  def filled_paragraphs
    [first_paragraph, second_paragraph, third_paragraph, fourth_paragraph].reject &:blank?
  end

  def signature
    return "faithfully" if addressee.blank?
    "sincerely"
  end
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :user

  scope :experiences, -> { where previous_experience: true }
  scope :non_experiences, -> { where previous_experience: false }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :cover_letters
  has_many :skills
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/cover_letters_controller.rb
class CoverLettersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @cover_letter = CoverLetter.find params[:id]
  end

  def create
    CoverLetter.create! permitted_data.merge(:user => current_user)
    redirect_to root_url
  end


  private
  def permitted_data
    params[:cover_letter].permit :addressee, :first_paragraph,
          :second_paragraph, :third_paragraph, :fourth_paragraph,
          :your_name
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def show
    @skill = Skill.find params[:id]
  end

  def create
    Skill.create! permitted_data.merge(:user => current_user)
    redirect_to root_url
  end


  private
  def permitted_data
    params[:skill].permit :name, :previous_experience
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cover_letters_helper.rb
module CoverLettersHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/cover_letters/index.html.erb
<div ng-controller="CoverLettersController">
  <h2>{{page_title}}</h2>
  <h3>Previous cover letters</h3>
  <ul>
    <% current_user.cover_letters.all.each do |letter| %>
      <li> To <%= link_to letter.addressee, cover_letter_url(letter) %> from <%= letter.your_name %></li>
    <% end %>
  </ul>

  <%= link_to "Create cover letter", new_cover_letter_url %>

  <h3> You have skills in: </h3>

  <ul>
    <% current_user.skills.non_experiences.all.each do |skill| %>
      <li> <%= link_to skill.name, skill_url(skill) %></li>
    <% end %>
  </ul>


  <h3> You have experience with: </h3>

  <ul>
    <% current_user.skills.experiences.all.each do |skill| %>
      <li> <%= link_to skill.name, skill_url(skill) %></li>
    <% end %>
  </ul>


  <%= link_to "Create skill", new_skill_url %>
</div>

app/views/cover_letters/new.html.erb
<div ng-controller="CoverLettersController">
  <h2>New Cover letter</h2>

  <h3> Your skills </h3>
  <ul>
    <% current_user.skills.each do |skill| %>
      <li>
        <%= label_tag skill.id, skill.name %>
        <%= check_box_tag skill.id, skill.name, false, 'ng-model' => "skills[#{skill.name.to_json}]", 'ng-change' => 'update_letter()' %>
      </li>
    <% end %>
  </ul>
  <% if current_user.skills.empty? %>
    <p> You don't seem to have any skills. That won't look good to employers! Why not learn some stuff? </p>
  <% end %>

  <%= link_to "Create skill", new_skill_url, :target => '_blank'%>


  <h3> Generated cover letter </h3>
  <%= form_for CoverLetter.new(user: current_user) do |form| %>
    <fieldset>
      <div>
        <%= form.label :addressee, "Who is this letter addressed to?" %>
        <%= form.text_field :addressee %>
      </div>
      <div>
        <%= form.label :first_paragraph %>
        <%= form.text_area :first_paragraph %>
      </div>
      <div>
        <%= form.label :second_paragraph %>
        <%= form.text_area :second_paragraph, :value => "{{skills_text}}" %>
      </div>
      <div>
        <%= form.label :third_paragraph %>
        <%= form.text_area :third_paragraph %>
      </div>
      <div>
        <%= form.label :fourth_paragraph %>
        <%= form.text_area :fourth_paragraph %>
      </div>
      <div>
        <%= form.label :your_name %>
        <%= form.text_field :your_name %>
      </div>
    </fieldet>

    <fieldset>
      <%= form.submit %>
    </fieldset>
  <% end %>
</div>

app/views/cover_letters/show.html.erb
<h2>Show cover letter</h2>

<p>
  Dear <strong><%= @cover_letter.addressee_or_generic %></strong>,
</p>

<% @cover_letter.filled_paragraphs.each do |paragraph| %>
  <p><strong><%= paragraph %></strong></p>
<% end %>

<p>
  Yours <strong><%= @cover_letter.signature %></strong>,
</p>

<p>
  <strong><%= @cover_letter.your_name %></strong>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app>
<head>
  <title>Coverletter</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= link_to "Home", root_url %>
    <%= link_to "Logout", destroy_user_session_url, :method => :delete %>
  </header>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/skills/new.html.erb
<div ng-controller="CoverLettersController">
  <h2>New Skill</h2>

  <%= form_for Skill.new(user: current_user) do |form| %>
    <fieldset>
      <div>
        <%= form.label :name, "What is the skill, e.g. 'Eating cake', 'Corporate cake consumption'" %>
        <%= form.text_field :name, :placeholder => 'eating cake', 'ng-model' => 'given_skill' %>
      </div>
      <div>
        <%= form.label :previous_experience, "{{skill_type}} {{given_skill}} (toggle checkbox to switch between skills / experiences)" %>
        <%= form.check_box :previous_experience, 'ng-model' => 'skill_type', 'ng-false-value' => 'I am skilled in' , 'ng-true-value' => 'I have experience with'%>
      </div>
    </fieldet>

    <fieldset>
      <%= form.submit %>
    </fieldset>
  <% end %>
</div>